services:
  client-pc:
    image: net-tools
    container_name: asdn-client-pc
    cap_add:
      - NET_ADMIN
    networks:
      internal-net:
        ipv4_address: 172.40.2.10
    command: bash -c "ip route del default && ip route add default via 172.40.2.254 && tail -f /dev/null"

  web-server:
    image: nginx:alpine
    container_name: asdn-web-server
    cap_add:
      - NET_ADMIN
    networks:
      dmz-net:
        ipv4_address: 172.40.1.10
    # Override default nginx command to set route and then start nginx
    command: /bin/sh -c "ip route del default && ip route add default via 172.40.1.254 && nginx -g 'daemon off;'"
        
  firewall:
    image: net-tools
    container_name: asdn-firewall
    cap_add:
      - NET_ADMIN
    networks:
      default: 
      dmz-net:
        ipv4_address: 172.40.1.254
      internal-net:
        ipv4_address: 172.40.2.254
    volumes:
      - ./firewall-init.sh:/firewall-init.sh:ro
    command: bash -c "/firewall-init.sh && tail -f /dev/null"


networks:
  dmz-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.1.0/24
  internal-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.2.0/24
  default:
