services:
  host-a:
    image: net-tools
    container_name: asdn-host-a
    cap_add:
      - NET_ADMIN
    networks:
      shared-net:
        ipv4_address: 172.50.0.10
    command: tail -f /dev/null

  host-b:
    image: net-tools
    container_name: asdn-host-b
    cap_add:
      - NET_ADMIN
    networks:
      shared-net:
        ipv4_address: 172.50.0.20
    command: tail -f /dev/null

networks:
  shared-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
