# Example provided for initializing FRR BGP inside Autonomous System 100
router bgp 100

 # Advertise our internal private network to the internet
 network 10.0.1.0/24

 # Define our peer relationship across the public link (pointing to r2's IP and asserting it belongs to AS 200)
 neighbor 10.0.0.2 remote-as 200
