#cloud-config

# 1. Modify the default user
users:
  - default
  - name: ubuntu
    groups: [docker]

# 2. Run shell commands on first boot
runcmd:
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - echo "Docker automated installation completed!"
