version: '3.8'

services:
  ryu-controller:
    build:
      context: ../docker
      dockerfile: Dockerfile.sdn
    container_name: asdn_ryu_lab18
    privileged: true
    volumes:
      - ./controller:/lab
    ports:
      - "6653:6653"
    command: >
      bash -c "ryu-manager /lab/ryu_campus.py"
