services:
  webapp:
    image: nginx:alpine
    container_name: asdn-frontend
    ports:
      - "8080:80"
    networks:
      - frontend-net
      - backend-net
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    
  database:
    image: postgres:15-alpine
    container_name: asdn-db
    environment:
      - POSTGRES_PASSWORD=secret
    networks:
      backend-net:
        ipv4_address: 172.30.2.10
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

networks:
  frontend-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/24
  backend-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.2.0/24
