# Kathará Lab Configuration

# Example provided for connecting a device's generic interface to a "Collision Domain" letter
r1[0]="A"

# TODO: Connect pc1's port 0 to Domain A
# ...

# TODO: Connect r1's port 1 to Domain B
# ...

# TODO: Connect r2's port 0 to Domain B
# ...

# TODO: Connect r2's port 1 to Domain C
# ...

# TODO: Connect pc2's port 0 to Domain C
# ...
