# Example provided indicating how to inject the dedicated SDN image for a specific Kathará node
s1[image]="kathara/sdn"
s1[0]="A"
s1[1]="B"

# TODO: Connect pc1 to Domain A
# ...

# TODO: Connect pc2 to Domain B
# ...
