services:
  host-a:
    image: net-tools
    container_name: asdn-host-a
    cap_add:
      - NET_ADMIN
    networks:
      net-alpha:
        ipv4_address: 10.5.1.10
    command: bash -c "ip route add 10.5.2.0/24 via 10.5.1.1 && tail -f /dev/null"

  host-b:
    image: net-tools
    container_name: asdn-host-b
    cap_add:
      - NET_ADMIN
    networks:
      net-beta:
        ipv4_address: 10.5.2.10
    command: bash -c "ip route add 10.5.1.0/24 via 10.5.2.1 && tail -f /dev/null"

  router:
    image: net-tools
    container_name: asdn-router
    cap_add:
      - NET_ADMIN
    networks:
      net-alpha:
        ipv4_address: 10.5.1.1
      net-beta:
        ipv4_address: 10.5.2.1
    volumes:
      - ./router-init.sh:/router-init.sh:ro
    command: bash -c "/router-init.sh && tail -f /dev/null"

networks:
  net-alpha:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.1.0/24
  net-beta:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.2.0/24
