version: '3.8'

services:
  mininet:
    build:
      context: ../docker
      dockerfile: Dockerfile.sdn
    container_name: asdn_mininet_lab05
    privileged: true
    volumes:
      - .:/lab
      - /lib/modules:/lib/modules:ro
    network_mode: "host"
    stdin_open: true
    tty: true
